[package]
org = "ORESoftware"
name = "rust-lib"
version = "0.1.0"
description = "rust-lib package"
license = "MIT"

[package.repository]
vcs = "git"
url = "https://github.com/ORESoftware/zed-pkg-test"

[publish]
exclude = []
