[package]
org = "ORESoftware"
name = "zed-pkg-test"
version = "0.1.0"
description = "Test repository for zed-pkg"
license = "MIT"

[package.repository]
vcs = "git"
url = "https://github.com/ORESoftware/zed-pkg-test"

[workspace]
members = ["node-app", "node-lib", "rust-app", "rust-lib"]

[publish]
exclude = ["benches/**"]
